version: '3.8'

services:
  openhab:
    image: "openhab/openhab:4.2.1"
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "./openhab_addons:/openhab/addons"
      - "./openhab_conf:/openhab/conf"
      - "./openhab_userdata:/openhab/userdata"
    environment:
      CRYPTO_POLICY: "unlimited"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"

  coap-server:
    build: ./coap-server
    container_name: coap-server
    restart: always
    ports:
      - "5683:5683/udp"
    volumes:
      - ./coap-server:/app
    command: python /app/server.py

  coap-proxy:
    build: ./coap-proxy
    container_name: coap-proxy
    restart: always
    depends_on:
      - coap-server
    ports:
      - "5000:5000"